uniq_neg.m:031: In clause for `unify(in, in, in, in, di, uo)':
uniq_neg.m:031:   in argument 3 of call to predicate `uniq_neg.occurs'/4:
uniq_neg.m:031:   mode error: variable [38;5;87m`STATE_VARIABLE_Store_0'[39;49m has
uniq_neg.m:031:   instantiatedness [38;5;203m`mostly_unique',[39;49m
uniq_neg.m:031:   expected instantiatedness was [38;5;40m`unique'.[39;49m
uniq_neg.m:031:   This kind of uniqueness mismatch is usually caused by doing
uniq_neg.m:031:   [38;5;226minput/output[39;49m or [38;5;226msome other kind of destructive update[39;49m [38;5;203min a[39;49m
uniq_neg.m:031:   [38;5;203mcontext where it can be backtracked over,[39;49m such as the
uniq_neg.m:031:   condition of an if-then-else.
